### ISSUE TITLE
AppleXRConcept.unity Cannot Use

### ISSUE THREAD

**Issue by ToddGitHub** [NovaUI-Unity/AppleXRConcept#1]
I want see the AppleXRConcept.unity scene, but the VisionOSDemo.apk Only have VisionOSDemo,unity, and i canot  build with free Trial.
hope can switch scene in apk

**Comment by adgray1** [comment]
Because the AppleXRConcept.unity scene in its current form is mostly "on rails", meaning only a subset of the UI is implemented and/or state dependent, as mention in the [README](https://github.com/NovaUI-Unity/AppleXRConcept/blob/main/README.md), we don't currently have plans to include it in the VisionOSDemo.apk. 

However, even with the free trial version of Nova, you can play around with the AppleXRConcept scene in VR over Oculus link!

**Comment by adgray1** [comment]
Just wanted to follow up here and let you know the latest version of the Nova - Free Trial (v2.0.0) does now include build support!
